# Generated by Django 5.2.3 on 2025-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_name", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("deal_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stage", models.CharField(max_length=100)),
                ("conversion_probability", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=255)),
                ("close_date", models.DateField()),
            ],
        ),
    ]
