# Generated by Django 5.2.3 on 2025-07-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="deal",
            old_name="deal_name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="close_date",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="conversion_probability",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="deal_value",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="stage",
        ),
        migrations.AddField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="deal",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="api.company",
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="api.company",
                    ),
                ),
            ],
        ),
    ]
