# Generated by Django 5.2.4 on 2025-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_company_rename_deal_name_deal_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="contacts",
            field=models.ManyToManyField(related_name="deals", to="api.customer"),
        ),
        migrations.AddField(
            model_name="deal",
            name="stage",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal"),
                    ("qualified", "Qualified"),
                    ("negotiation", "Negotiation"),
                ],
                default="proposal",
                max_length=20,
            ),
        ),
    ]
