# Generated by Django 5.2.4 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_deal_close_date_deal_contacts_deal_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Technology", "Technology"),
                    ("Healthcare", "Healthcare"),
                    ("Finance", "Finance"),
                    ("Sports", "Sports"),
                    ("Manufacturing", "Manufacturing"),
                    ("Retail", "Retail"),
                    ("Energy", "Energy"),
                    ("Aviation", "Aviation"),
                    ("Education", "Education"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
