# Generated by Django 5.2.4 on 2025-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_company_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("healthcare", "Healthcare"),
                    ("finance", "Finance"),
                    ("sports", "Sports"),
                    ("manufacturing", "Manufacturing"),
                    ("retail", "Retail"),
                    ("energy", "Energy"),
                    ("aviation", "Aviation"),
                    ("other", "Other"),
                    ("real estate", "Real Estate"),
                    ("food & beverage", "Food & Beverage"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
