# Generated by Django 5.2.4 on 2025-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_company_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
