# Generated by Django 5.2.4 on 2025-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customer_phone_number_customer_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
